name: Feature Request
description: Suggest features for this project.
title: "[Feature request]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What do you need?
      description: Tell us what functionality you would like added/modified?
      value: "I want the CLI to do my homework for me."
    validations:
      required: true
