name: Question
description: Ask us questions about this project.
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: description
    attributes:
      label: What is your question?
      value: "After reading the documentation, I am still not clear how to get X working. I tried this, this, and that."
    validations:
      required: true
